apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsmlrdeploy1
  labels:
    app: carsmlrdeployapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mlcontainer25nov2022
          image: mlcontainer25nov2022.azurecr.io/cars_fuel:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: carmlr-service1
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: web